Add support for TS project not located at the root of the repo.
allegro/typescript-strict-plugin pull request #45
Opened 2022-10-13 13:38 UTC by neenjaw

This is the PR followup for the discussion in #44

### Overview of the changes:

1. Add support for the tsc `--project` flag to use non-root located `tsconfig.json` files to scope the plugin
2. Some tests added, with respect to changes in the project

2022-10-13 13:42 UTC, neenjaw commented
If accepted for merge, would you also be willing to add a label `hacktoberfest-accepted` so that this would count toward my contributions?

2022-10-14 08:32 UTC, KostkaBrukowa approved these changes

2022-10-14 08:33 UTC, KostkaBrukowa requested changes
Can you also bump up a version in package.json and update the changelog? It looks great and we could release new version

2022-10-14 13:33 UTC, neenjaw commented
Can do, bump it up a minor version?

2022-10-14 14:35 UTC, KostkaBrukowa approved these changes

2022-10-14 14:35 UTC, merged